import type { Buddy } from './types'

export const gyms = [
  'Any gym',
  'MADabolic Noda',
  'The Fitness Factory of Charlotte',
  'South End Training Lab',
  'University Performance Gym',
]

export const workouts = [
  'Any workout',
  'Leg day',
  'Upper body',
  'Push',
  'Pull',
  'Full body',
  'Cardio',
  'Core',
  'Functional training',
  'Rock climbing',
  'Tennis',
  'Badminton',
]

export const buddies: Buddy[] = [
  {
    id: 1,
    name: 'Maya',
    initials: 'MA',
    age: 26,
    gender: 'Woman',
    gym: 'MADabolic Noda',
    neighborhood: 'NoDa',
    experience: 'Intermediate',
    weight: 148,
    workouts: ['Leg day', 'Full body', 'Core'],
    availability: ['Mon 6:30 PM', 'Wed 6:30 PM', 'Sat 10:00 AM'],
    bio: 'I remember how intimidating my first gym visit felt. Happy to meet at the entrance, show you where things are, and get a solid workout in.',
    firstTimerFriendly: true,
    buddyMode: 'Either',
    rating: 4.9,
    sessions: 18,
    accent: 'coral',
  },
  {
    id: 2,
    name: 'Jordan',
    initials: 'JO',
    age: 29,
    gender: 'Man',
    gym: 'South End Training Lab',
    neighborhood: 'South End',
    experience: 'Advanced',
    weight: 176,
    workouts: ['Push', 'Pull', 'Upper body'],
    availability: ['Tue 7:00 AM', 'Thu 7:00 AM', 'Sun 11:00 AM'],
    bio: 'Consistent lifter, low-pressure gym partner. I can help you get comfortable with the layout, but I am not a trainer.',
    firstTimerFriendly: true,
    buddyMode: 'Workout buddy',
    rating: 4.8,
    sessions: 31,
    accent: 'blue',
  },
  {
    id: 3,
    name: 'Nia',
    initials: 'NI',
    age: 25,
    gender: 'Woman',
    gym: 'The Fitness Factory of Charlotte',
    neighborhood: 'Noda',
    experience: 'Beginner',
    weight: 158,
    workouts: ['Cardio', 'Full body', 'Functional training'],
    availability: ['Mon 5:45 PM', 'Fri 5:45 PM', 'Sat 9:00 AM'],
    bio: 'Still learning too. Looking for another person who wants to build a routine without feeling like we have to know everything already.',
    firstTimerFriendly: true,
    buddyMode: 'Either',
    rating: 5.0,
    sessions: 7,
    accent: 'purple',
  },
  {
    id: 4,
    name: 'Chris',
    initials: 'CH',
    age: 28,
    gender: 'Man',
    gym: 'University Performance Gym',
    neighborhood: 'University City',
    experience: 'Intermediate',
    weight: 169,
    workouts: ['Leg day', 'Pull', 'Core'],
    availability: ['Wed 7:15 PM', 'Thu 7:15 PM', 'Sun 3:00 PM'],
    bio: 'Mostly strength training. I like focused sessions, good conversation between sets, and showing up consistently.',
    firstTimerFriendly: false,
    buddyMode: 'Workout buddy',
    rating: 4.7,
    sessions: 22,
    accent: 'green',
  },
  {
    id: 5,
    name: 'Avery',
    initials: 'AV',
    age: 27,
    gender: 'Non-binary',
    gym: 'NoDa Fitness House',
    neighborhood: 'Plaza Midwood',
    experience: 'Intermediate',
    weight: 154,
    workouts: ['Rock climbing', 'Functional training', 'Full body'],
    availability: ['Tue 6:00 PM', 'Fri 6:00 PM', 'Sun 1:00 PM'],
    bio: 'Happy to be the familiar face at the door. I prefer relaxed sessions and people who care more about consistency than ego.',
    firstTimerFriendly: true,
    buddyMode: 'Walk-in companion',
    rating: 4.9,
    sessions: 15,
    accent: 'amber',
  },
  {
    id: 6,
    name: 'Sam',
    initials: 'SA',
    age: 24,
    gender: 'Woman',
    gym: 'South End Training Lab',
    neighborhood: 'Dilworth',
    experience: 'First timer',
    weight: 142,
    workouts: ['Cardio', 'Leg day', 'Core'],
    availability: ['Mon 7:30 PM', 'Thu 7:30 PM', 'Sat 12:00 PM'],
    bio: 'I have been putting off joining a commercial gym because I do not want to go alone. Looking for someone to figure it out with me.',
    firstTimerFriendly: true,
    buddyMode: 'Walk-in companion',
    rating: 5.0,
    sessions: 2,
    accent: 'pink',
  },
]
